-- ---------------------------------------------------------------------------
-- MARAIS store schema. Run this in the Supabase SQL editor.
--
-- Safe to run more than once: every statement is idempotent, and the seed data
-- is guarded so re-running will not duplicate the catalog.
--
-- Note the GRANT statements. Postgres checks table level privileges BEFORE it
-- evaluates a row level security policy, so a perfectly correct policy on a
-- table with no GRANT still fails with 42501 permission denied. Policies and
-- grants are two separate mechanisms and both are required.
-- ---------------------------------------------------------------------------

create table if not exists public.products (
  id           bigint generated by default as identity primary key,
  name         text          not null,
  category     text          not null,
  audience     text          not null,
  price        numeric(10,2) not null check (price >= 0),
  image_url    text,
  description  text,
  fabric       text,
  sizes        text[]        not null default '{}',
  is_active    boolean       not null default true,
  created_at   timestamptz   not null default now()
);

create table if not exists public.orders (
  id               bigint generated by default as identity primary key,
  reference        text          not null unique,
  user_id          uuid          references auth.users(id) on delete set null,
  customer_email   text          not null,
  customer_name    text          not null,
  customer_phone   text,
  shipping_address jsonb         not null,
  shipping_method  text          not null default 'standard',
  shipping         numeric(10,2) not null default 0 check (shipping >= 0),
  subtotal         numeric(10,2) not null check (subtotal >= 0),
  total            numeric(10,2) not null check (total >= 0),
  items            jsonb         not null,
  notes            text,
  status           text          not null default 'pending',
  created_at       timestamptz   not null default now()
);

create index if not exists orders_user_id_idx    on public.orders (user_id);
create index if not exists orders_reference_idx  on public.orders (reference);

create table if not exists public.subscribers (
  id         bigint generated by default as identity primary key,
  email      text        not null unique,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------
alter table public.products    enable row level security;
alter table public.orders      enable row level security;
alter table public.subscribers enable row level security;

-- Catalog: readable by anyone, writable by nobody through the API.
drop policy if exists "active products are publicly readable" on public.products;
create policy "active products are publicly readable"
  on public.products for select
  using (is_active = true);

grant select on public.products to anon, authenticated;

-- Orders: a signed in customer may read their OWN rows and nothing else.
-- Writes never happen through this path; the Express server inserts with the
-- service role key, which bypasses RLS entirely.
drop policy if exists "customers read their own orders" on public.orders;
create policy "customers read their own orders"
  on public.orders for select
  to authenticated
  using (user_id = auth.uid());

grant select on public.orders to authenticated;
revoke all on public.orders from anon;

-- Subscribers: server only. No policy for anon or authenticated means neither
-- can read or write it even holding the anon key.
revoke all on public.subscribers from anon, authenticated;

-- A role allowed to insert also needs the sequence.
grant usage, select on all sequences in schema public to authenticated;

-- ---------------------------------------------------------------------------
-- Seed catalog. Matches src/data/products.js so the API and the offline
-- fallback show the same range. Guarded so re-running does nothing.
-- ---------------------------------------------------------------------------
insert into public.products (name, category, audience, price, image_url, description, fabric, sizes)
select * from (values
  ('Wool Overcoat', 'Outerwear', 'Women', 248::numeric,
   'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=900&q=80',
   'Double breasted overcoat in Portuguese wool, lined for warmth without the bulk.',
   '82% wool, 18% recycled polyamide', array['XS','S','M','L','XL']),
  ('Silk Slip Dress', 'Dresses', 'Women', 128::numeric,
   'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=900&q=80',
   'Bias cut silk with adjustable straps. Wears alone or layers under knitwear.',
   '100% mulberry silk', array['XS','S','M','L']),
  ('Relaxed Linen Shirt', 'Shirts', 'Men', 98::numeric,
   'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=900&q=80',
   'Garment washed linen with a soft collar and dropped shoulder.',
   '100% European flax linen', array['S','M','L','XL','XXL']),
  ('Tailored Trousers', 'Trousers', 'Men', 138::numeric,
   'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=900&q=80',
   'Mid rise wool blend trousers with a tapered leg and a single front pleat.',
   '68% wool, 30% viscose, 2% elastane', array['28','30','32','34','36']),
  ('Cashmere Crew', 'Knitwear', 'Women', 168::numeric,
   'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=900&q=80',
   'Two ply cashmere, brushed for softness, in a relaxed crew neck.',
   '100% grade A cashmere', array['XS','S','M','L']),
  ('Selvedge Denim Jacket', 'Outerwear', 'Men', 158::numeric,
   'https://images.unsplash.com/photo-1543076447-215ad9ba6923?auto=format&fit=crop&w=900&q=80',
   'Rigid selvedge denim, built to break in and soften with wear.',
   '100% cotton selvedge denim, 13.5oz', array['S','M','L','XL']),
  ('Pleated Midi Skirt', 'Skirts', 'Women', 112::numeric,
   'https://images.unsplash.com/photo-1583496661160-fb5886a13d77?auto=format&fit=crop&w=900&q=80',
   'Fluid pleating in a satin back crepe with a concealed side zip.',
   '100% recycled polyester crepe', array['XS','S','M','L','XL']),
  ('Leather Tote', 'Bags', 'Accessories', 198::numeric,
   'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=900&q=80',
   'Vegetable tanned leather with reinforced handles and an internal zip pocket.',
   'Vegetable tanned full grain leather', array['One size'])
) as seed(name, category, audience, price, image_url, description, fabric, sizes)
where not exists (select 1 from public.products);

-- ---------------------------------------------------------------------------
-- Verify by impersonation rather than by reading the policy and assuming.
-- ---------------------------------------------------------------------------
-- set local role anon;
-- select count(*) from public.products;      -- expect 8
-- select count(*) from public.orders;        -- expect permission denied
-- reset role;
--
-- set local role authenticated;
-- set local request.jwt.claims = '{"sub":"<a-real-user-uuid>","role":"authenticated"}';
-- select count(*) from public.orders;        -- expect only that user's rows
-- reset role;
